[phases.setup]
nixPkgs = ["nodejs_22", "npm-9_x"]

[phases.install]
cmds = ["cd server && rm -rf node_modules && npm install"]

[phases.build]
cmds = ["cd server && npm run build"]

[start]
cmd = "cd server && npm start"
