[phases.setup]
nixPkgs = ["nodejs_20", "python3"]

[phases.install]
cmds = [
  "npm install",
  "cd server && npm install"
]

[phases.build]
cmds = [
  "npm run build:all"
]

[start]
cmd = "npm start"
